### ISSUE TITLE
setup/fuzz.exe - libFuzzer: deadly signal

### ISSUE THREAD

**Issue by chkeita** [chkeita/glowing-octo-lana#2]
## Files

* input: [crash-1c03e3922631a3de723ccc14367e9f22ca25dbc9](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-1c03e3922631a3de723ccc14367e9f22ca25dbc9)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [d29e2902bb79dbdef100dd3e73a369e6532734496f00a8cecc033dd911256d76.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=d29e2902bb79dbdef100dd3e73a369e6532734496f00a8cecc033dd911256d76.json)

## Repro

 `onefuzz --endpoint https://chkeitaonefuzz2.azurewebsites.net repro create_and_connect oft-reports-cecbd958a1f257688f9768edaaf6c94d d29e2902bb79dbdef100dd3e73a369e6532734496f00a8cecc033dd911256d76.json`

## Call Stack

```#0 0x4d5ea1 in __sanitizer_print_stack_trace (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4d5ea1)
#1 0x454f3b in fuzzer::PrintStackTrace() (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x454f3b)
#2 0x439d43 in fuzzer::Fuzzer::CrashCallback() (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x439d43)
#3 0x7ffff783d97f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1297f)
#4 0x7ffff6ab6fb6 in __libc_signal_restore_set /build/glibc-S9d2JN/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
#5 0x7ffff6ab6fb6 in raise /build/glibc-S9d2JN/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
#6 0x7ffff6ab8920 in abort /build/glibc-S9d2JN/glibc-2.27/stdlib/abort.c:79
#7 0x4fd7a8 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:62:9
#8 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
#9 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
#10 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
#11 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
#12 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
#13 0x41db59 in _start (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x41db59)
```

## ASAN Log

```INFO: Seed: 2989834058
INFO: Loaded 1 modules   (22 inline 8-bit counters): 22 [0x738f28, 0x738f3e), 
INFO: Loaded 1 PC tables (22 PCs): 22 [0x5144a8,0x514608), 
setup/fuzz.exe: Running 1 inputs 1 time(s) each.
Running: /onefuzz/31d26042-d084-40f8-88ce-7fb847fcf606/task_crashes_1/crash-1c03e3922631a3de723ccc14367e9f22ca25dbc9
==4908== ERROR: libFuzzer: deadly signal
    #0 0x4d5ea1 in __sanitizer_print_stack_trace (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4d5ea1)
    #1 0x454f3b in fuzzer::PrintStackTrace() (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x454f3b)
    #2 0x439d43 in fuzzer::Fuzzer::CrashCallback() (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x439d43)
    #3 0x7ffff783d97f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1297f)
    #4 0x7ffff6ab6fb6 in __libc_signal_restore_set /build/glibc-S9d2JN/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
    #5 0x7ffff6ab6fb6 in raise /build/glibc-S9d2JN/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
    #6 0x7ffff6ab8920 in abort /build/glibc-S9d2JN/glibc-2.27/stdlib/abort.c:79
    #7 0x4fd7a8 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:62:9
    #8 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
    #9 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
    #10 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
    #11 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
    #12 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #13 0x41db59 in _start (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x41db59)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-489838c1be5fb62787a260efe3f5e50792171fa1](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-489838c1be5fb62787a260efe3f5e50792171fa1)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [56746ec9a91f685f893a0c50be0673325474edd2140d69e3ff39c6b1e7522508.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=56746ec9a91f685f893a0c50be0673325474edd2140d69e3ff39c6b1e7522508.json)
