### ISSUE TITLE
setup/fuzz.exe - AddressSanitizer: double-free (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd36d) in free

### ISSUE THREAD

**Issue by chkeita** [chkeita/glowing-octo-lana#5]
## Files

* input: [crash-2cc7a6da1a57facb3246fad289fdff34391a8a46](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-2cc7a6da1a57facb3246fad289fdff34391a8a46)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [34b35d61d6a9a35c719158fa2bdf674138af09d1d67dda7ca7c091c27bbd96b0.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=34b35d61d6a9a35c719158fa2bdf674138af09d1d67dda7ca7c091c27bbd96b0.json)

## Repro

 `onefuzz --endpoint https://chkeitaonefuzz2.azurewebsites.net repro create_and_connect oft-reports-cecbd958a1f257688f9768edaaf6c94d 34b35d61d6a9a35c719158fa2bdf674138af09d1d67dda7ca7c091c27bbd96b0.json`

## Call Stack

```#0 0x4cd36d in free (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd36d)
#1 0x4fd5c5 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:43:56
#2 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
#3 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
#4 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
#5 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
#6 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
#7 0x41db59 in _start (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x41db59)
```

## ASAN Log

```INFO: Seed: 32736466
INFO: Loaded 1 modules   (22 inline 8-bit counters): 22 [0x738f28, 0x738f3e), 
INFO: Loaded 1 PC tables (22 PCs): 22 [0x5144a8,0x514608), 
setup/fuzz.exe: Running 1 inputs 1 time(s) each.
Running: /onefuzz/31d26042-d084-40f8-88ce-7fb847fcf606/task_crashes_1/crash-2cc7a6da1a57facb3246fad289fdff34391a8a46
=================================================================
==4932==ERROR: AddressSanitizer: attempting double-free on 0x602000000010 in thread T0:
    #0 0x4cd36d in free (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd36d)
    #1 0x4fd5c5 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:43:56
    #2 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
    #3 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
    #4 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
    #5 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
    #6 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #7 0x41db59 in _start (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x41db59)

0x602000000010 is located 0 bytes inside of 4-byte region [0x602000000010,0x602000000014)
freed by thread T0 here:
    #0 0x4cd36d in free (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd36d)
    #1 0x4fd5b6 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:43:47
    #2 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
    #3 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
    #4 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
    #5 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
    #6 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310

previously allocated by thread T0 here:
    #0 0x4cd5ed in malloc (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd5ed)
    #1 0x4fd5a0 in LLVMFuzzerTestOneInput /home/runner/work/onefuzz/onefuzz/src/integration-tests/libfuzzer/simple.c:43:26
    #2 0x43b271 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x43b271)
    #3 0x423767 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x423767)
    #4 0x429741 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x429741)
    #5 0x4557a2 in main (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4557a2)
    #6 0x7ffff6a99bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: double-free (/onefuzz/blob-containers/fuzz27ee6imdmr5gy/fuzz.exe+0x4cd36d) in free
==4932==ABORTING
```

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-4aefb63c8b4eb902a5e4cd519eb1bc3327dec930](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-4aefb63c8b4eb902a5e4cd519eb1bc3327dec930)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [14d483427e11d805c7dba3529fa04be5c809c9ae2b8883a7b4a2052116dfb84b.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=14d483427e11d805c7dba3529fa04be5c809c9ae2b8883a7b4a2052116dfb84b.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-a7085f763eef0f6d35674da2a449d699481d606c](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-a7085f763eef0f6d35674da2a449d699481d606c)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [3bd18da2d528c7ab74dd017a403c4e69fcd9ad7d4c8a1d220126534d7da5fc26.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=3bd18da2d528c7ab74dd017a403c4e69fcd9ad7d4c8a1d220126534d7da5fc26.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-755687bdb9fb03ac795fc9cd2462784e80513924](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-755687bdb9fb03ac795fc9cd2462784e80513924)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [869bdc533e51fb69eed76df02ca6eec65b1f1f9747349b72db672b541fdf014c.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=869bdc533e51fb69eed76df02ca6eec65b1f1f9747349b72db672b541fdf014c.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-e437a4f0143e85e32b3baf4287dd85f8627fd6e5](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-e437a4f0143e85e32b3baf4287dd85f8627fd6e5)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [32b6bcbcf251d5acea01e5497121601c5c3d0a269446ff7693d4672b2ddd4c92.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=32b6bcbcf251d5acea01e5497121601c5c3d0a269446ff7693d4672b2ddd4c92.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-a575dbdc7620d1fb12a50fd8315ac6a7ee40a4d2](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-a575dbdc7620d1fb12a50fd8315ac6a7ee40a4d2)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [5da38ea601e6c782596479b7fd9c7a575186e5dd58c9b9e1854010a59a24b2cb.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=5da38ea601e6c782596479b7fd9c7a575186e5dd58c9b9e1854010a59a24b2cb.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-2746c18675ce3cbc61249111a32b765b2400d8f0](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-2746c18675ce3cbc61249111a32b765b2400d8f0)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [d10f621dd90335cd2a0f3eb036ba0b8727e58577ed3d86d1151d7c0ea8f4ea9b.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=d10f621dd90335cd2a0f3eb036ba0b8727e58577ed3d86d1151d7c0ea8f4ea9b.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-9bcb0c1c8a21b66018f196b7390d7703cda5119b](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-9bcb0c1c8a21b66018f196b7390d7703cda5119b)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [05e91114abd6d1e01a90f596f9c6e5f3fc39b91b42a8ff269e006843a402cd95.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=05e91114abd6d1e01a90f596f9c6e5f3fc39b91b42a8ff269e006843a402cd95.json)

**Comment by chkeita** [comment]
Duplicate found.

* input: [crash-ed6b6f73b09388780be6e2b7a49af79517087787](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-crashes-cecbd958a1f257688f9768edaaf6c94d&filename=crash-ed6b6f73b09388780be6e2b7a49af79517087787)
* exe: [setup/fuzz.exe]( https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-setup-8a9128aaf9e550249583860d45eb3697&filename=fuzz.exe)
* report: [56d91d30258298e2a5dfcb6cc81e2593eb69ed589d7d2dafd00b71bf89956dde.json](https://chkeitaonefuzz2.azurewebsites.net/api/download?container=oft-reports-cecbd958a1f257688f9768edaaf6c94d&filename=56d91d30258298e2a5dfcb6cc81e2593eb69ed589d7d2dafd00b71bf89956dde.json)
